### ISSUE TITLE
Dev: Port argument in CLI does not work

### ISSUE THREAD

**Issue by frandiox** [cfworker/cfworker#100]
Running `cfworker run -w -p 1337 ./src/index.ts` throws `RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN`.

I think I've seen this before in some other CLI recently, so it might be an issue with a dependency used for the CLI (commander?).

**Comment by jdanyow** [comment]
fixed in 1.6.8
