### ISSUE TITLE
 Could not load virtual:multi-entry.js: invalid glob pattern

### ISSUE THREAD

**Issue by madruga8** [cfworker/cfworker#116]
hello,

im getting this error on cfwoker while on wrangler it runs ok... i would like to debug with cfworkers

$ cfworker run 
⚠ @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
✖ Error: Could not load virtual:multi-entry.js: invalid glob pattern: 

my webpack  config is: 

var glob = require("glob");

module.exports = {
    target: "webworker",
    devtool: "cheap-module-source-map", // avoid "eval": Workers environment doesn’t allow it
    entry: glob.sync("./src/service/**/*.js"),
    mode: "development",
    module: {
        rules: [
            {
                test: /\_\_client\.js$/i,
                use: [
                    {
                        loader: 'raw-loader',
                        options: {
                            esModule: false,
                        },
                    },
                ],
            },
        ],
    },
}

**Comment by jdanyow** [comment]
hi @madruga8, this is not enough info to diagnose. Could you try again with the latest `@cfworker/dev`?

cfworker doesn't use your webpack config- you provide it an entry point module and it will bundle your application automatically using rollup.
```sh
cfworker run my-worker.js --watch --inspect
```
```sh
cfworker run my-typescript-worker.ts --watch --inspect
```

```
Usage: cfworker run [options] [input...]

run worker script

Options:
  -p, --port <port>      set the port to serve on (default: 7000)
  -w, --watch            enable watch mode (default: false)
  -i, --inspect          open browser window with devtools enabled (default: false)
  -n --nocheck           disable diagnostic checks on TypeScript code
  -s --site <directory>  static site directory
  -k --kv <filename>     kv json file (default: [])
  -h, --help             display help for command
```
