### ISSUE TITLE
Feature: Password hasing using Web Crypto API

### ISSUE THREAD

**Issue by bladerunner41** [cfworker/cfworker#12]
Could I suggest adding a Password hashing function using the native [Web crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Pbkdf2Params) to complement the other authentication capabilities for those using workers for authentication e.g. user signup, login, password reset.

I assume using the native optimised API would run with the paid 50ms CPU time where as regular node/npm modules for bcrypt, argon2 would not.

**Comment by jdanyow** [comment]
@bladerunner41 which package is this issue in reference to?

I agree, native web crypto API is the way to go. [@cfworker/jwt](https://github.com/cfworker/cfworker/blob/master/packages/jwt/README.md) uses the crypto API to verify JWT signatures.  [@cfworker/uuid](https://github.com/cfworker/cfworker/blob/master/packages/uuid/README.md) uses the crypto API to generate random numbers.

**Comment by bladerunner41** [comment]
hi @jdanyow apologies - I'm suggesting to create a new package - @cfworker/PBKDF2 or similar with functions to securely hash a password (for saving) and validate passwords against a stored hash as a higher level API.  

Similar logic to providing the @cfworker/base64url package for common algorithms that exist in node.js.  If using node, people would typically use a standard node module or npm package to hash passwords but those don’t work with CF workers, just like there is no base64 encoding equivalent.

**Comment by jdanyow** [comment]
Got it. Something similar to https://www.npmjs.com/package/pbkdf2

**Comment by bladerunner41** [comment]
Yes - correct.

**Comment by jdanyow** [comment]
Closing this as out of scope for now.
