### ISSUE TITLE
Feature: web-router POST request body parsing

### ISSUE THREAD

**Issue by bladerunner41** [cfworker/cfworker#13]
A possible enhancement to remove boilerplate code for router POST request handeling would be to provide a parsed request body baed upon the content-type as per this code from [another CF worker project](https://github.com/panda-sandeep/telex/blob/master/index.js#L16):

```
async function readRequestBody(request) {
    const { headers } = request
    const contentType = headers.get('content-type')
    if (contentType.includes('application/json')) {
      const body = await request.json()
      return body;
    } else if (contentType.includes('application/text')) {
      const body = await request.text()
      return body
    } else if (contentType.includes('text/html')) {
      const body = await request.text()
      return body
    } else if (contentType.includes('form')) {
      const formData = await request.formData()
      let body = {}
      for (let entry of formData.entries()) {
        body[entry[0]] = entry[1]
      }
      return JSON.stringify(body)
    } else {
      let myBlob = await request.blob()
      var objectURL = URL.createObjectURL(myBlob)
      return objectURL
    }
}
```

**Comment by jdanyow** [comment]
After thinking about this more, I'm going to close. There's a few issues with this:
1. The parsed request body isn't convenient, consumers will still need logic to determine whether it's an object, string, form data, etc.
2. Automatically parsing the request body is bad for perf, it breaks scenarios where the worker was only going to stream the response to the client.
3. Minor- the above code has a bug, should be `text/plain` not `application/text`.
