### ISSUE TITLE
When visiting my cloudflare worker: `cfworker No fetch handler attached.

### ISSUE THREAD

**Issue by ben-xD** [cfworker/cfworker#132]
Unfortunately when visiting the cloudflare worker URL provided by the browser page which automatically opens, I got a html page with `No fetch handler attached.`. I'm not sure how to fix it.

To run this, I used: `webpack --watch & cfworker run worker.js -p 14000 --watch --inspect`. 

I have the code in [this](https://github.com/ben-xD/ably-cloudflare-workers/tree/cfworker) branch of the repo, the index.js is [here](https://github.com/ben-xD/ably-cloudflare-workers/blob/cfworker/src/index.ts). I am simply doing:
```js
addEventListener('fetch', (event) =&gt; {    const url = new URL(event.request.url)
    const fetchEvent = event as FetchEvent;    fetchEvent.respondWith(new Response("HELLO there"))    
    return
  }
})
```

Note: it works when running without cfworker: `webpack && wrangler preview --env test`

Thank you for your time and help :)

**Comment by jdanyow** [comment]
Question to help troubleshoot:

What happens after you've already used webpack to build worker.js, then execute the following on it's own:

```
cfworker run worker.js -p 14000 --watch --inspect
```

**Comment by ben-xD** [comment]
Hi @jdanyow , it has the same issue. I shouldn't have complicated it by adding webpack. :)

**Comment by jdanyow** [comment]
Any errors in the console of the cfworker devtools window?

Do you really have the following characters: 
`=&gt;`
Instead of:
`=>`?

**Comment by jdanyow** [comment]
@ben-xD I think the command should be something like:
```
cfworker run dist/worker.js -p 14000 --watch --inspect
```

Based on your webpack config:
https://github.com/ben-xD/ably-cloudflare-workers/blob/main/webpack.config.js#L9-L12

**Comment by ben-xD** [comment]
Thanks a lot @jdanyow, that fixed it :)
