### ISSUE TITLE
JWT: JWKS Caching approach ineffective

### ISSUE THREAD

**Issue by bladerunner41** [cfworker/cfworker#14]
The approach to JWKS caching is largely ineffective in a CF workers environment, as the cache won’t persist across requests/invocations and cause added latency to fetch the JWKS file externally each time.

Suggest enhancing the code to:
1. Use the CF Worker API to cache the XHR result (JWKS.json)
2. Support passing in a static JSON object of the JWKS XHR as per this library due to long expiry of the signing certificate as per [this example ](https://gist.github.com/bcnzer/04620abc992da72f83f6f1c61d71c93c#file-worker-js-L175)
3. Also supporting a pre-shared HMAC-based secret - in a lot of cases this more common and far easier than RSA.  It is perfectly suitable within an organisation for 1st party apps were both the IdP and RP are controlled by the same party.  RSA would be essential for 3rd Party apps so the app itself can self generate a token as the IdP.

**Comment by jdanyow** [comment]
The cache is effective. Here's an example:
```js
let i = 0;

addEventListener('fetch', event => {
    i++;
    event.respondWith(new Response(JSON.stringify(i), {
        status: 200,
        headers: {
            'content-type': 'application/json'
        }
    }));
});
```
https://memory-cache.jdanyow.workers.dev/

**Comment by bladerunner41** [comment]
Thanks @jdanyow.  Agree there is some caching across execution, but CF worker context resets in 60 seconds if there aren't any requests. For most services with low traffic, a lot of requests will have a 100-200ms cold start.
