### ISSUE TITLE
The read session is not available for the input session token

### ISSUE THREAD

**Issue by Inrixia** [cfworker/cfworker#155]
When querying `cosmos` via `@cfworker/cosmos` every now and then all requests will fail with code "NotFound" and the error `The read session is not available for the input session token`. After retrying several times everything returns to normal.

Any idea on why this happening and how to fix it?

**Comment by Inrixia** [comment]
This is the query I am doing btw.

```ts
await req.env.cosmos.getDocument({ docId: id, partitionKey: id, collId: "users" }).then((res) => res.json()))
```

**Comment by Inrixia** [comment]
It also seems that simply retrying is not enough, attempting to create the document, getting a conflict error and then querying for it again works. But just retrying will always return the error...

**Comment by jdanyow** [comment]
What consistencyLevel are you using when constructing the `CosmosClient`? If it's session (the default), you could try preserving the client's sessionToken across worker instances via a durable object or kv. This way if a new worker starts it can enlist in session used by the previous worker.

https://github.com/cfworker/cfworker/blob/main/packages/cosmos/src/client.ts#L82

**Comment by jdanyow** [comment]
Disregard my previous comment- I found some code in the SDK that handles retry for this specific issue.
When the response's status code is 404 and an `x-ms-substatus` response header is present with value `1002` we need to clear the CosmosClient's sessionToken and retry. I'll create a PR.

**Comment by Inrixia** [comment]
Ah awesome. Thanks for the help. Lmk if I can do anything, happy to help test a fix

**Comment by jdanyow** [comment]
Shipped a fix in `@cfworker/cosmos@1.10.0`- let me know if you continue to encounter this issue.

**Comment by Inrixia** [comment]
Will let you know as soon as I get the chance to test it. Thanks!

**Comment by jdanyow** [comment]
awesome! please do let me know if this is resolved.

**Comment by Inrixia** [comment]
Haven't extensively tested but seems to be fixed thanks :)

Will update if I run into it again
