### ISSUE TITLE
v1.9.0 @cfworker/json-schema/dist/validator.js - Error when importing

### ISSUE THREAD

**Issue by stoneroll6** [cfworker/cfworker#156]
The following code in validator.js:
```
export class Validator {
    schema;
    draft;
    shortCircuit;
    lookup;
    constructor(schema, draft = '2019-09', shortCircuit = true) {
        this.schema = schema;
        this.draft = draft;
        this.shortCircuit = shortCircuit;
        this.lookup = dereference(schema);
    // rest of code
    }
```
causes a loader error when attempting to `import { Validator } from '@cfworker/json-schema'`. It appears JS does not understand `schema, draft, shortCircuit, lookup` public instance fields appearing before constructor. Issue is fixed after removing.

Working validator.js code:
```
export class Validator {
     constructor(schema, draft = '2019-09', shortCircuit = true) {
        this.schema = schema;
        this.draft = draft;
        this.shortCircuit = shortCircuit;
        this.lookup = dereference(schema);
    // rest of code
    }
```

**Comment by jdanyow** [comment]
Those are [public instance fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields#public_instance_fields). Where are you seeing the error? The 1.9.0 code runs in the browser/workers without any compilation.

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>GistRun</title>
  <script type="module">
    import { Validator } from 'https://cdn.jsdelivr.net/npm/@cfworker/json-schema@1.9.0/dist/index.js';
    const validator = new Validator({ type: 'number' });
    let result = validator.validate(1);
    document.body.insertAdjacentHTML('beforeend', `<pre><code>${JSON.stringify(result, null, 2)}</code></pre>`);
    result = validator.validate('hello');
    document.body.insertAdjacentHTML('beforeend', `<pre><code>${JSON.stringify(result, null, 2)}</code></pre>`);
  </script>
</head>
<body>
  <h1>Hello world!</h1>
</body>
</html>
```
https://gist.run/?id=a4f6c9b5854d10bcfe9c39f7345bcd10

**Comment by stoneroll6** [comment]
The error appeared while attempting to publish a Worker via Wrangler from a local machine (VSCode). I had npm installed @cfworker/json-schema. Running npm v6.14.14

```
WebPack Error: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.
| import { dereference } from './dereference.js';
| import { validate } from './validate.js';
| export class Validator {
>    schema;
```

**Comment by apeiniger** [comment]
@stoneroll6 Could you share how you solved this issue? Having the same problem. I'm using @cfworker/json-schema in my create react app project and since 1.9.0 it's throwing this error when building.

**Comment by stoneroll6** [comment]
@apeiniger Yes, please see original post above for details. If the validator.js file is throwing the error when building, you can try removing the public instance fields. 

Not sure if this will cause errors down the line, but schema validation was working after doing so.

**Comment by jdanyow** [comment]
@apeiniger @stoneroll6 try 1.10.1. I've updated the build to target ES2021 rather than ESNEXT which has the effect of removing the instance fields in the output. This should give your build tooling some time to catch up. Please do let me know if this resolves the issue.

**Comment by stoneroll6** [comment]
@jdanyow Updated to 1.10.1, and it works like a charm. Thank you!
