### ISSUE TITLE
RFC: Using json-schema for OpenAPI validation

### ISSUE THREAD

**Issue by saibotsivad** [cfworker/cfworker#178]
Given an [OpenAPI](https://spec.openapis.org/oas/v3.1.0) definition, I would like to validate a request (query params, path params, etc.) using `@cfworker/json-schema`.

I've developed a way to do it, but it requires me to use the `validate` function instead of `new Validator`, e.g. it looks something like this:

```js
import { validate } from '@cfworker/json-schema'
import definition from './open-api-definition.json'

// manually making the `lookup` map with hashes
const lookup = {
    '#/components/parameters/taskId': definition.components.parameters.taskId.schema,
    '#/components/schemas/task': definition.components.schemas.task,
    // etc for the rest of the OpenAPI document
    // (of course, I have a lib to generate the `lookup` map)
}

// then for each request run the validate function
const { valid, errors } = validate(
    // pass in the JSON.parse'd body as the data
    request.body,
    // the schema id is based on the request
    // (again, I have a lib to handle that as well)
    lookup['#/components/schemas/task'],
    '2019-09',
    lookup,
    false
)
```

(I made [a gist](https://gist.github.com/saibotsivad/3c1734c7aea85c88b21e276266d31ad6) that describes this in more detail, if anyone is interested.)

This is working alright, but since the `validate` function isn't documented in the README.md at all, it makes me nervous that I'm "reaching inside" and that'll be brittle and break on a minor/patch version bump.

## Proposal

I would like to add the `validate` function to the README.md file, to give (myself and others) confidence that it will be considered a first-class function, with respect to version bumps.

I'd make a PR to update the README, if that's alright? Nothing too serious, just adding the `validate` function as a listed export, to make it clear.

**Comment by jdanyow** [comment]
@saibotsivad closing this, happy to re-open if you want to collab on a solution.
