### ISSUE TITLE
Migrate @cfworker/sentry to prepareStackTrace

### ISSUE THREAD

**Issue by jdanyow** [cfworker/cfworker#179]
~~https://github.com/errwischt/stacktrace-parser/blob/master/src/stack-trace-parser.js~~
https://v8.dev/docs/stack-trace-api

**Comment by nikosgpet** [comment]
I am not getting it. Why manually parse the stack instead of using the V8 stack trace API as done here: https://github.com/borderless/worker-sentry/blob/master/src/index.ts

**Comment by jdanyow** [comment]
Ha simple- I didn't know about the prepareStackTrace trick- thanks for the tip 🤙

**Comment by jdanyow** [comment]
tried using @borderless/worker-sentry, which uses prepareStackTrace- seems to lose a lot of stack information in comparison to parsing the .stack. Closing this.
