### ISSUE TITLE
Request: support API token instead of API keys

### ISSUE THREAD

**Issue by galaxy4public** [cfworker/cfworker#22]
CloudFlare's API Key provides highly privileged access with no ability to manage the possible negative impact.  It would be much much better if `cfworker` could support the tokens instead (or in addition to).

Basically, instead of using e-mail and API key in the requests to the CloudFlare's API you could use:
```
Authorization: Bearer API_TOKEN_HERE
```
Then access would depend on whatever is configured to that token (in the worst case access would be equivalent to the API Key).

**Comment by jdanyow** [comment]
implemented in 1.6.8
