### ISSUE TITLE
JWT enhancements

### ISSUE THREAD

**Issue by Inrixia** [cfworker/cfworker#220]
I have a repo with helper classes for dealing with JWT's in cloudflare workers.
https://github.com/Inrixia/CFWorker-JWT

I just noticed that there is also one here that is fairly popular, the helper libraries in my repo have some additional features compared to what's supported here such as using keyvault to cache JWKS and type support for extending the payload with login flows from Auth0.

Im interested in migrating to use the JWT module here but would need the KV caching and type extension features for it to be feasible. Would you be interested in accepting a PR adding these features?

**Comment by jdanyow** [comment]
I think you could use this lib and pass in your own key resolver:
https://github.com/cfworker/cfworker/blob/main/packages/jwt/src/parse.ts#L16

Your key resolver could use getJwks and cache in KV as-needed.
https://github.com/cfworker/cfworker/blob/main/packages/jwt/src/jwks.ts#L8

Thoughts?

**Comment by Inrixia** [comment]
Ah yes that looks perfect. Ill experiment with this and let you know how it goes!

**Comment by jdanyow** [comment]
@Inrixia closing- happy to reopen if needed
