### ISSUE TITLE
Localization on json-schema validator

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [cfworker/cfworker#235]
Is there any way to customize error message in `@cfworker/json-schema` or to enable internationalization on the library error messages?

**Comment by jdanyow** [comment]
@giovanni-bertoncelli not at this time, what's the use case?

**Comment by giovanni-bertoncelli** [comment]
I was using this library in an Angular application in order to validate forms. The application is multilingual and I need to print out the JSON schema validation error in the current language selected, but it seems that this package does not allow it. I had no other choice but to use ajv with a i18n plugin..

**Comment by jdanyow** [comment]
Got it- ajv is a better validator, @cfworker/json-schema is really only for scenarios where you can't precompile the schemas.
