### ISSUE TITLE
[json-schema] tsconfig-base referenced in tsconfig.json but not in package

### ISSUE THREAD

**Issue by SvanteRichter** [cfworker/cfworker#237]
Hello,

tsconfig-base is referenced in tsconfig.json but not included in the json-schema npm package. This leads to a warning in my non-standard build process (using esbuild directly on the package).

Would it be possible to either not include tsconfig.json in the package or include tsconfig-base?

Thanks!

**Comment by jdanyow** [comment]
this is finally fixed!
