### ISSUE TITLE
Vite CJS / ESModule warning

### ISSUE THREAD

**Issue by jhwz** [cfworker/cfworker#240]
When running a svelte-kit server with the project `vite` outputs the following warning:

```sh
@cfworker/uuid doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
```
It's no big problem, setting:
```ts
ssr: {
    noExternal: ['@cfworker/uuid']
}
```
in `vite.config.js` resolves the issue, but would be nice to have the warning removed.

**Comment by JoshZA** [comment]
This affects other modules as well

`@cfworker/cosmos doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
`

**Comment by houmark** [comment]
Hi @jdanyow — I hit this issue with `@cfworker/uuid` while trying out Remix using Vite for Cloudflare Pages.

I'm not sure if the fix is as simple as it looks on the surface, but I'd love to see a fix that makes Vite happy.

**Comment by jdanyow** [comment]
this is finally fixed!
