### ISSUE TITLE
Feature Request: Enable Configurable Clock Skew in JWT Parsing

### ISSUE THREAD

**Issue by EisenbergEffect** [cfworker/cfworker#271]
I recently updated both Node.js and Wrangler. After doing so, I started having auth errors on my local dev machine (not in prod), ultimately stemming from clock skew. To get around this problem, I temporarily updated the `node_modules` source of [the parse code](https://github.com/cfworker/cfworker/blob/main/packages/jwt/src/parse.ts#L7) in `@cfworker/jwt` to change the skew from 30 to 60 seconds.

It would be nice to be able to pass the allowed skew to [the parseJwt function](https://github.com/cfworker/cfworker/blob/main/packages/jwt/src/parse.ts#L12) for situations like this.

**Comment by jdanyow** [comment]
Good call- now `parseJwt` accepts a single "options" object parameter, with an optional `skewMs` property to enable changing the skew allowance used to validate iat, nbf, and exp. The default skew allowance has been bumped from 30 to 60 seconds.

**Comment by EisenbergEffect** [comment]
Thank you!
