### ISSUE TITLE
Any plans to create a package for Azure Table Storage?

### ISSUE THREAD

**Issue by therealjordanlee** [cfworker/cfworker#309]
Hi @jdanyow 

Just wondering if there are any plans to release a client for Azure Table Storage?
From using the SDK for .NET, the tableClient can be used for both CosmosDB and Table storage, so I assume the APIs for both services are pretty similar.
https://learn.microsoft.com/en-us/dotnet/api/overview/azure/data.tables-readme?view=azure-dotnet

The official SDK for js unfortunately doesn't work on cloudflare workers. There was an issue raised on their forums which never got resolved:
https://community.cloudflare.com/t/uncaught-referenceerror-document-is-not-defined/688910

**Comment by jdanyow** [comment]
Hey @therealjordanlee - sorry to say there are no plans for table storage at this time.

You could look into using the table storage rest api, links below. This is the approach I used for developing the CosmosDB client.
- https://learn.microsoft.com/en-us/rest/api/storageservices/query-tables
- https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-requests-to-azure-storage
