### ISSUE TITLE
json-schema: Please enable an option to report all errors

### ISSUE THREAD

**Issue by phb** [cfworker/cfworker#63]
Hi,

First off, thanks for writing the json-schema component, it is very speedy and is perfect for our usecase. (Can't use AJV as the compilation step of the schema is too slow and our schema is dynamic)

We need an option to report all errors in the schema, instead of stopping and only reporting the "top level" errors. (the 'stop' variable in validate.ts)

Is this something you would consider to implement or accept a patch for?

Other projects have similar options
- tv4: validateMultiple
- ajv: allErrors option

Let me know
/Johan

**Comment by jdanyow** [comment]
Nice- glad you're finding this useful. I'd accept a PR to disable the short-circuit evaluation.

How about we add `private readonly shortCircuit = true` to the Validator constructor:
https://github.com/cfworker/cfworker/blob/718240d2d61043e71232f2ad2a58c65a6aad776e/packages/json-schema/src/validator.ts#L8-L11

Then add `shortCircuit = true` to the validator function arguments after the `lookup` arg:
https://github.com/cfworker/cfworker/blob/718240d2d61043e71232f2ad2a58c65a6aad776e/packages/json-schema/src/validate.ts#L14-L23

Once those two things are in place all the `stop = true` assignments can switch to `stop = shortCircuit` and Validator.validate can pass in the shortCircuit arg.

Thoughts?

**Comment by phb** [comment]
Sounds good to me -- thanks for the detailed proposal. I'll submit a patch later today.

**Comment by jdanyow** [comment]
thanks for the PR, shipped in `@cfworker/json-schema@1.3.0`
