### ISSUE TITLE
ES Module Error for json-schema

### ISSUE THREAD

**Issue by kungfoolabs** [cfworker/cfworker#81]
Hi,

I am using Typescript in my project and getting an error from ESM. I believe the issue is that Typescript is transpiling and doesn't recognize that json-schema is type `module` so it tries to use `require`. Is there a workaround for this? 

Error below:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /node_modules/@cfworker/json-schema/dist/index.js
require() of ES modules is not supported.
require() of /node_modules/@cfworker/json-schema/dist/index.js from /web/build/server.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /node_modules/@cfworker/json-schema/package.json.
```

**Comment by jdanyow** [comment]
Hard to say without knowing more about your build setup. `@cfworker/json-schema` is an ES module and has `"type": "module"` in it's package.json.
