### ISSUE TITLE
@cfworker/sentry build issue

### ISSUE THREAD

**Issue by oddui** [cfworker/cfworker#82]
When building with the wrangler tool, webpack complains cannot find `@cfworker/uuid`.

```
> wrangler dev

👀  ./node_modules/@cfworker/sentry/dist/capture.js
Module not found: Error: Can't resolve '@cfworker/uuid' in '.../node_modules/@cfworker/sentry/dist'
resolve '@cfworker/uuid' in '.../node_modules/@cfworker/sentry/dist'
```

I think `@cfworker/sentry` should have `@cfworker/uuid` as a dependency in package.json.

**Comment by jdanyow** [comment]
fixed in [@cfworker/sentry 1.6.2](https://www.npmjs.com/package/@cfworker/sentry/v/1.6.2). thanks for reporting
