### ISSUE TITLE
@cfworker/sentry source maps support

### ISSUE THREAD

**Issue by oddui** [cfworker/cfworker#86]
I'm having difficulty figuring out how to show original code in sentry. I have setup the release value in @cfworker/sentry and uploaded source maps to the release in sentry.

Errors in sentry do not show the original code:

![image](https://user-images.githubusercontent.com/720036/100424858-4e570500-30e2-11eb-84f3-06f5923addb4.png)

I have tried to upload the source map as `~/worker.js.map` and `/worker.js.map`:

![image](https://user-images.githubusercontent.com/720036/100424915-66c71f80-30e2-11eb-9bf4-c926384cb4de.png)

Do any one have this working correctly?

Thank you.

**Comment by jdanyow** [comment]
I haven't implemented source map support in the `@cfworker/sentry` package. It hasn't been something I've needed because I use rollup to build my worker, without minification/uglification.

**Comment by oddui** [comment]
Hi @jdanyow, will this be something you will look into?

I tried to change the stacktrace filename to `/worker.js` by changing
```diff
    exception: {
      values: [
        {
          type: parsed.name,
          value: parsed.message,
          stacktrace: {
            frames: parsed.stack.reverse().map(s => ({
-             filename: s.url,
+             filename: `/${s.url}`,
              function: s.func,
              lineno: s.line,
              colno: s.column
            }))
          }
        }
      ]
    },
```

It didn't work.

**Comment by jdanyow** [comment]
hey @oddui, apologies, this is not something I have the bandwidth to prioritize anytime soon. I'd happily accept a PR if you find a solution.

**Comment by oddui** [comment]
@jdanyow no problem. I've turned off minification in my wrangler build but it would be nice to see the original typescript code.

Would it be ok if I replace tracekit.ts with [stacktrace-js package](https://github.com/stacktracejs/stacktrace.js) to parse the error?

**Comment by jdanyow** [comment]
I took a look at stacktrace-js, I'd rather not use it directly because it contains much more code than we need due to support for all sorts of browsers. One of stacktrace-js's dependencies is error-stack-parser, is there anything in the parser code that we need to adopt in @cfworker/sentry?
https://github.com/stacktracejs/error-stack-parser/blob/master/error-stack-parser.js#L51-L84

> I did try to use toucan-js but it's api doesn't work well with @cfworker/web
Good to know- anything specific that needs to change in web?

**Comment by jdanyow** [comment]
closing- I recommend folks try https://github.com/robertcepa/toucan-js if they require more advanced sentry integration. cfworker/sentry is intentionally a more limited, lightweight subset of functionality.
