### ISSUE TITLE
JWT: Support for x509 PEM cert

### ISSUE THREAD

**Issue by m3hari** [cfworker/cfworker#89]
Hello! Thanks for the nice work!

To provide a bit of backgorund , I am trying to use firebase authentication on cf workers environment.
So I was trying to use this package until I find out, firebase-auth doesn't provide `JWKS.json` instead they provide "public keys in (pem) format , to verify signature. Here are the keys for reference, https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com

Is there a plan to support verifying JWT with public keys in this package?
If you can give some hint on **how to generate jwk from public keys**, or if you think there is another way to do it,  I would be happy to create a PR for the feature.

Thanks

**Comment by jdanyow** [comment]
The keys you linked appear to be PEM encoded x509 certs. I found a [blog post](https://blog.engelke.com/2014/10/21/web-crypto-and-x-509-certificates/) that describes how to parse these and eventually use [importKey](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/importKey) to get a CryptoKey. Assuming all that works you could then export the CryptoKey as a jwk that `@cfworker/jwt` can use.
```js
// ... logic from blog post ...
// ...
// ...
const publicKey: CryptoKey = await crypto.subtle.importKey( ... logic from blog post ...);
// export as jwk that @cfworker/jwt can use.
const jwk = await crypto.subtle.exportKey('jwk', publicKey);
```
Then you can pass the jwk to importKey. `issuer` should match the `iss` value found in the JWTs you're trying to validate.
https://github.com/cfworker/cfworker/blob/2292f528ac85397f538256447d8e00e840c4cdeb/packages/jwt/src/jwks.ts#L20-L25

Hope that helps!

**Comment by m3hari** [comment]
@jdanyow We were able to convert x509 certificate to `CryptoKey` following that blog post, but at the end it turns out firebase 
publish JWK with standard format [here](https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com) , though they don't mention it in the docs.

As you can see firebase don't use `wellknow/jwk.json` path and they publish set of keys in array instead of single JWK object.

I will make a PR to allow supporting such cases. Basically I think allowing an optional callback function to parse the JWKs is good solution.

**Comment by jdanyow** [comment]
sounds good, thanks for the PRs

**Comment by katopz** [comment]
> @jdanyow We were able to convert x509 certificate to `CryptoKey` following that blog post, but at the end it turns out firebase
> publishes JWKs with standard format [here](https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com) , though they don't mention it in the docs. So we decided to use that.
> 
> As you can see firebase don't publish the keys in the standard `/.well-known/jwks.json` path.
> 
> I will make a PR to cover such cases. I think adding optional keyset parameter will make it flexible.

I facing this issue now, any update on this?

**Comment by jdanyow** [comment]
@katopz try the instructions here and let us know how it goes https://github.com/cfworker/cfworker/issues/89#issuecomment-743472265

**Comment by katopz** [comment]
> @katopz try the instructions here and let us know how it goes [#89 (comment)](https://github.com/cfworker/cfworker/issues/89#issuecomment-743472265)

Here's my result without optimize on mbp
```
decodeJwt: 0.7978515625 ms
decode: 0.1240234375 ms
import: 11.0859375 ms
exportKey: 1.425048828125 ms
importKey: 1.60595703125 ms
verifyJwtSignature: 15.384033203125 ms

sum: 32.32470703125 ms
```
Anyway the code itself seem to be all native function already.
Maybe it can optimize (or cached hash on k/v) somehow.

Thanks! 👍

**Comment by leesus** [comment]
How do we verify Firebase tokens, given @m3hari PR was closed?

**Comment by jdanyow** [comment]
You can use cfworker’s importKey function- mentioned in https://github.com/cfworker/cfworker/issues/89#issuecomment-743472265
